# Generated by Django 4.2.30 on 2026-08-10 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        ('vitals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessed_at', models.DateTimeField()),
                ('observation_count', models.IntegerField(default=1, help_text='Number of vital observations used')),
                ('news2_total', models.IntegerField()),
                ('news2_hr_score', models.IntegerField()),
                ('news2_rr_score', models.IntegerField()),
                ('news2_spo2_score', models.IntegerField()),
                ('news2_bp_score', models.IntegerField()),
                ('news2_temp_score', models.IntegerField()),
                ('trend_window_4', models.JSONField(blank=True, default=dict, help_text='Last 4 observations analysis')),
                ('trend_window_8', models.JSONField(blank=True, default=dict, help_text='Last 8 observations analysis')),
                ('trend_window_12', models.JSONField(blank=True, default=dict, help_text='Last 12 observations analysis')),
                ('trend_score', models.IntegerField(default=0, help_text='Score from trend analysis (0+)')),
                ('multi_param_score', models.IntegerField(default=0, help_text='Score from multiple vitals worsening together')),
                ('multi_param_details', models.JSONField(blank=True, default=dict, help_text='Which parameters moving together')),
                ('combined_risk', models.IntegerField(help_text='NEWS2 + trend + multi-parameter combined')),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk'), ('critical', 'Critical')], max_length=20)),
                ('explanation_text', models.TextField(blank=True, help_text='Human-readable explanation of why this risk level')),
                ('decision_logic', models.JSONField(blank=True, default=dict, help_text='Step-by-step reasoning in structured format')),
                ('algorithm_version', models.CharField(default='1.0.0', max_length=20)),
                ('configuration_version', models.CharField(default='1.0.0', max_length=20)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessments', to='patients.patient')),
                ('vital_signs', models.ManyToManyField(related_name='risk_assessments', to='vitals.vitalsigns')),
            ],
            options={
                'verbose_name_plural': 'Risk Assessments',
                'ordering': ['-assessed_at'],
                'indexes': [models.Index(fields=['patient', '-assessed_at'], name='vitals_risk_patient_143e91_idx')],
            },
        ),
    ]
