# Generated by Django 4.2.30 on 2026-08-10 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitals', '0002_riskassessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskassessment',
            name='multi_param_pattern',
            field=models.CharField(default='stable', help_text='Pattern of multi-parameter worsening', max_length=50),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='recommendation',
            field=models.TextField(blank=True, help_text='Clinical recommendation based on risk level'),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='trend_level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=20),
        ),
    ]
