# Generated by Django 4.2.30 on 2026-08-11 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        ('vitals', '0003_riskassessment_multi_param_pattern_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictiveRiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prediction_timestamp', models.DateTimeField(help_text='When prediction was made')),
                ('current_heart_rate', models.FloatField(blank=True, null=True)),
                ('current_respiratory_rate', models.FloatField(blank=True, null=True)),
                ('current_oxygen_saturation', models.FloatField(blank=True, null=True)),
                ('current_bp_systolic', models.FloatField(blank=True, null=True)),
                ('current_temperature', models.FloatField(blank=True, null=True)),
                ('forecast_24h_heart_rate', models.FloatField(blank=True, null=True)),
                ('forecast_24h_respiratory_rate', models.FloatField(blank=True, null=True)),
                ('forecast_24h_oxygen_saturation', models.FloatField(blank=True, null=True)),
                ('forecast_24h_bp_systolic', models.FloatField(blank=True, null=True)),
                ('forecast_24h_temperature', models.FloatField(blank=True, null=True)),
                ('forecast_24h_news2_score', models.IntegerField(blank=True, null=True)),
                ('forecast_48h_heart_rate', models.FloatField(blank=True, null=True)),
                ('forecast_48h_respiratory_rate', models.FloatField(blank=True, null=True)),
                ('forecast_48h_oxygen_saturation', models.FloatField(blank=True, null=True)),
                ('forecast_48h_bp_systolic', models.FloatField(blank=True, null=True)),
                ('forecast_48h_temperature', models.FloatField(blank=True, null=True)),
                ('forecast_48h_news2_score', models.IntegerField(blank=True, null=True)),
                ('forecast_72h_heart_rate', models.FloatField(blank=True, null=True)),
                ('forecast_72h_respiratory_rate', models.FloatField(blank=True, null=True)),
                ('forecast_72h_oxygen_saturation', models.FloatField(blank=True, null=True)),
                ('forecast_72h_bp_systolic', models.FloatField(blank=True, null=True)),
                ('forecast_72h_temperature', models.FloatField(blank=True, null=True)),
                ('forecast_72h_news2_score', models.IntegerField(blank=True, null=True)),
                ('hours_to_critical', models.FloatField(blank=True, null=True)),
                ('projected_critical_timestamp', models.DateTimeField(blank=True, null=True)),
                ('vitals_at_risk', models.JSONField(blank=True, default=list, help_text='List of vital names approaching critical thresholds')),
                ('critical_vital_first', models.CharField(blank=True, max_length=50, null=True)),
                ('critical_vital_first_hours', models.FloatField(blank=True, null=True)),
                ('forecast_confidence', models.FloatField(default=0.7, help_text='Model confidence (0-1) based on data quality')),
                ('historical_readings_used', models.IntegerField(default=0, help_text='Number of historical readings used for forecast')),
                ('trajectory_level', models.CharField(choices=[('stable', 'Stable'), ('slow_deterioration', 'Slow Deterioration'), ('moderate_deterioration', 'Moderate Deterioration'), ('rapid_deterioration', 'Rapid Deterioration'), ('critical_within_24h', 'Critical Within 24h')], default='stable', max_length=30)),
                ('recommended_actions', models.JSONField(blank=True, default=list, help_text='List of recommended clinical actions')),
                ('intervention_window_hours', models.FloatField(blank=True, help_text='Recommended hours to intervene before critical state', null=True)),
                ('forecast_details', models.JSONField(blank=True, default=dict, help_text='Detailed forecast data (trends, model outputs, etc.)')),
                ('based_on_vital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predictions', to='vitals.vitalsigns')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictive_risk_assessments', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Predictive Risk Assessment',
                'verbose_name_plural': 'Predictive Risk Assessments',
                'ordering': ['-prediction_timestamp'],
                'indexes': [models.Index(fields=['patient', '-prediction_timestamp'], name='vitals_pred_patient_4e6805_idx'), models.Index(fields=['trajectory_level', '-prediction_timestamp'], name='vitals_pred_traject_be0a68_idx')],
            },
        ),
    ]
