# Generated by Django 4.2.30 on 2026-08-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitals', '0004_predictiveriskassessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictiveriskassessment',
            name='forecast_30d_bp_systolic',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predictiveriskassessment',
            name='forecast_30d_heart_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predictiveriskassessment',
            name='forecast_30d_news2_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predictiveriskassessment',
            name='forecast_30d_oxygen_saturation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predictiveriskassessment',
            name='forecast_30d_respiratory_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predictiveriskassessment',
            name='forecast_30d_temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predictiveriskassessment',
            name='forecast_365d_bp_systolic',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predictiveriskassessment',
            name='forecast_365d_heart_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predictiveriskassessment',
            name='forecast_365d_news2_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predictiveriskassessment',
            name='forecast_365d_oxygen_saturation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predictiveriskassessment',
            name='forecast_365d_respiratory_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predictiveriskassessment',
            name='forecast_365d_temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predictiveriskassessment',
            name='forecast_7d_bp_systolic',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predictiveriskassessment',
            name='forecast_7d_heart_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predictiveriskassessment',
            name='forecast_7d_news2_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predictiveriskassessment',
            name='forecast_7d_oxygen_saturation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predictiveriskassessment',
            name='forecast_7d_respiratory_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predictiveriskassessment',
            name='forecast_7d_temperature',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
