# Generated by Django 4.2.30 on 2026-08-19 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitals', '0007_week3_patient_forecast'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='patientforecast',
            new_name='vitals_pati_patient_e8bf7f_idx',
            old_name='vitals_patientforecast_patient_created_idx',
        ),
        migrations.RenameIndex(
            model_name='patientforecast',
            new_name='vitals_pati_vital_n_d916da_idx',
            old_name='vitals_patientforecast_vital_created_idx',
        ),
        migrations.AlterField(
            model_name='patientbaselinedata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='patientforecast',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
