# Generated by Django 4.2.30 on 2026-08-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitals', '0008_rename_vitals_patientforecast_patient_created_idx_vitals_pati_patient_e8bf7f_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskassessment',
            name='news2_consciousness_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vitalsigns',
            name='consciousness',
            field=models.CharField(choices=[('A', 'Alert'), ('C', 'Confusion (new)'), ('V', 'Responds to Voice'), ('P', 'Responds to Pain'), ('U', 'Unresponsive')], default='A', help_text='ACVPU scale - the 6th NEWS2 parameter', max_length=1),
        ),
    ]
