# Generated by Django 4.2.30 on 2026-08-19 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffavailability',
            name='role',
        ),
        migrations.RemoveField(
            model_name='staffavailability',
            name='staff_name',
        ),
        migrations.AddField(
            model_name='staffavailability',
            name='staff',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['nurse', 'care_assistant']}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduler_availability', to=settings.AUTH_USER_MODEL),
        ),
    ]
