# Generated by Django 4.2.30 on 2026-06-08 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vitals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_size', models.IntegerField(choices=[(4, '4 readings'), (8, '8 readings'), (12, '12 readings')], default=8, help_text='Number of readings in trend window')),
                ('news2_trend_slope', models.FloatField(help_text='Rate of change in NEWS2 score (per reading)')),
                ('news2_avg_current', models.FloatField(help_text='Average NEWS2 over current window')),
                ('news2_avg_previous', models.FloatField(help_text='Average NEWS2 over previous window')),
                ('temp_trend', models.FloatField(blank=True, null=True)),
                ('hr_trend', models.FloatField(blank=True, null=True)),
                ('rr_trend', models.FloatField(blank=True, null=True)),
                ('spo2_trend', models.FloatField(blank=True, null=True)),
                ('bp_systolic_trend', models.FloatField(blank=True, null=True)),
                ('severity', models.CharField(choices=[('stable', 'Stable - No trend'), ('improving', 'Improving - Downward trend'), ('declining', 'Declining - Upward trend'), ('critical', 'Critical - Rapid decline detected')], default='stable', max_length=20)),
                ('risk_score', models.IntegerField(default=0, help_text='Combined risk from trends and current values')),
                ('analysed_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trend_analyses', to='patients.patient')),
            ],
            options={
                'verbose_name_plural': 'Trend Analyses',
                'ordering': ['-analysed_at'],
            },
        ),
        migrations.CreateModel(
            name='DeteriorationEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(help_text='e.g., NEWS2_SCORE_RECORDED, TREND_CALCULATED, ALERT_TRIGGERED', max_length=100)),
                ('severity_at_event', models.CharField(help_text='Patient severity at time of event', max_length=20)),
                ('data_snapshot', models.JSONField(help_text='Snapshot of vitals/scores at time of event')),
                ('notes', models.TextField(blank=True)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_logs', to='patients.patient')),
            ],
            options={
                'verbose_name_plural': 'Deterioration Event Logs',
                'ordering': ['-logged_at'],
            },
        ),
        migrations.CreateModel(
            name='DeteriorationAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('threshold_breach', 'NEWS2 Threshold Breach (>=7)'), ('trend_rise', 'Rapid Trend Rise (slope > 0.5)'), ('sustained_elevation', 'Sustained Elevation (2+ readings high)'), ('combined_risk', 'Combined Risk Factors'), ('ml_prediction', 'ML Model Prediction')], max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'CRITICAL')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active - Not reviewed'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('suppressed', 'Suppressed')], default='active', max_length=20)),
                ('trigger_value', models.FloatField(help_text='NEWS2 score or trend slope that triggered alert')),
                ('trigger_reason', models.CharField(help_text='Why this alert was triggered', max_length=255)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('is_suppressed', models.BooleanField(default=False)),
                ('suppression_reason', models.CharField(blank=True, help_text='Why this alert was suppressed', max_length=255)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deterioration_alerts', to='patients.patient')),
                ('related_trend', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deterioration_alerts.trendanalysis')),
                ('related_vital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vitals.vitalsigns')),
            ],
            options={
                'verbose_name_plural': 'Deterioration Alerts',
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertSuppressionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('time_based', 'Suppress for X minutes'), ('count_based', 'Suppress if >X alerts in Y minutes')], max_length=20)),
                ('suppress_minutes', models.IntegerField(default=15, help_text='Minutes to suppress after first alert')),
                ('alert_threshold', models.IntegerField(default=3, help_text='Number of alerts before suppression kicks in')),
                ('time_window_minutes', models.IntegerField(default=30, help_text='Time window for counting alerts')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Notes on why this rule was created')),
                ('patient', models.ForeignKey(blank=True, help_text='Leave blank for system-wide rule', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppression_rules', to='patients.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='trendanalysis',
            index=models.Index(fields=['patient', '-analysed_at'], name='deteriorati_patient_09c6f6_idx'),
        ),
        migrations.AddIndex(
            model_name='trendanalysis',
            index=models.Index(fields=['severity'], name='deteriorati_severit_80a700_idx'),
        ),
        migrations.AddIndex(
            model_name='deteriorationeventlog',
            index=models.Index(fields=['patient', '-logged_at'], name='deteriorati_patient_ec8056_idx'),
        ),
        migrations.AddIndex(
            model_name='deteriorationeventlog',
            index=models.Index(fields=['event_type'], name='deteriorati_event_t_a667cd_idx'),
        ),
        migrations.AddIndex(
            model_name='deteriorationalert',
            index=models.Index(fields=['patient', 'status'], name='deteriorati_patient_5c7f56_idx'),
        ),
        migrations.AddIndex(
            model_name='deteriorationalert',
            index=models.Index(fields=['priority', 'status'], name='deteriorati_priorit_af5ffe_idx'),
        ),
        migrations.AddIndex(
            model_name='deteriorationalert',
            index=models.Index(fields=['triggered_at'], name='deteriorati_trigger_500073_idx'),
        ),
    ]
