# Generated by Django 4.2.30 on 2026-07-31 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vitals', '0001_initial'),
        ('deterioration_alerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deteriorationalert',
            name='related_vital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deterioration_alerts', to='vitals.vitalsigns'),
        ),
    ]
