# Generated by Django 4.2.30 on 2026-08-10 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vitals', '0003_riskassessment_multi_param_pattern_and_more'),
        ('deterioration_alerts', '0002_alter_deteriorationalert_related_vital'),
    ]

    operations = [
        migrations.AddField(
            model_name='deteriorationalert',
            name='risk_assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='vitals.riskassessment'),
        ),
        migrations.AlterField(
            model_name='deteriorationalert',
            name='alert_type',
            field=models.CharField(choices=[('threshold_breach', 'NEWS2 Threshold Breach (>=7)'), ('trend_rise', 'Rapid Trend Rise (slope > 0.5)'), ('sustained_elevation', 'Sustained Elevation (2+ readings high)'), ('combined_risk', 'Combined Risk Factors'), ('ml_prediction', 'ML Model Prediction'), ('research_deterioration_detection', 'Research Deterioration Detection (Phase 4)')], max_length=50),
        ),
    ]
